"""baseline schema

Revision ID: 9ebc4da1d161
Revises: 
Create Date: 2026-09-11 02:44:07.559999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebc4da1d161'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_predictions_agent_id'), 'agent_predictions', ['agent_id'], unique=False)
    op.create_index('ix_agent_predictions_exec_agent', 'agent_predictions', ['execution_id', 'agent_id'], unique=False)
    op.create_index(op.f('ix_agent_predictions_execution_id'), 'agent_predictions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_predictions_snapshot_id'), 'agent_predictions', ['snapshot_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('execution_id', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('health', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('llm_backed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent'), 'agent_runs', ['agent'], unique=False)
    op.create_index('ix_agent_runs_agent_started', 'agent_runs', ['agent', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_execution_id'), 'agent_runs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_started_at'), 'agent_runs', ['started_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_username', sa.String(length=100), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('customer_ref', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_customer_ref'), 'conversations', ['customer_ref'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=False)
    op.create_table('customer_memory',
    sa.Column('customer_ref', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_ref')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('customer_unique_id', sa.String(length=32), nullable=False),
    sa.Column('customer_zip_code_prefix', sa.Integer(), nullable=False),
    sa.Column('customer_city', sa.String(length=100), nullable=False),
    sa.Column('customer_state', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_customer_unique_id'), 'customers', ['customer_unique_id'], unique=False)
    op.create_index(op.f('ix_customers_customer_zip_code_prefix'), 'customers', ['customer_zip_code_prefix'], unique=False)
    op.create_table('dataco_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_segment', sa.String(length=50), nullable=True),
    sa.Column('customer_city', sa.String(length=100), nullable=True),
    sa.Column('customer_state', sa.String(length=50), nullable=True),
    sa.Column('customer_country', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('order_region', sa.String(length=50), nullable=True),
    sa.Column('order_country', sa.String(length=100), nullable=True),
    sa.Column('order_city', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('shipping_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('shipping_mode', sa.String(length=50), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('late_delivery_risk', sa.Integer(), nullable=False),
    sa.Column('days_for_shipping_real', sa.Float(), nullable=True),
    sa.Column('days_for_shipment_scheduled', sa.Float(), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=False),
    sa.Column('order_profit', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_dataco_orders_customer_id'), 'dataco_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_dataco_orders_late_delivery_risk'), 'dataco_orders', ['late_delivery_risk'], unique=False)
    op.create_index(op.f('ix_dataco_orders_market'), 'dataco_orders', ['market'], unique=False)
    op.create_index(op.f('ix_dataco_orders_order_date'), 'dataco_orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_dataco_orders_order_region'), 'dataco_orders', ['order_region'], unique=False)
    op.create_index(op.f('ix_dataco_orders_order_status'), 'dataco_orders', ['order_status'], unique=False)
    op.create_index(op.f('ix_dataco_orders_shipping_mode'), 'dataco_orders', ['shipping_mode'], unique=False)
    op.create_index(op.f('ix_dataco_orders_source'), 'dataco_orders', ['source'], unique=False)
    op.create_table('geolocation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geolocation_zip_code_prefix', sa.Integer(), nullable=False),
    sa.Column('geolocation_lat', sa.Float(), nullable=False),
    sa.Column('geolocation_lng', sa.Float(), nullable=False),
    sa.Column('geolocation_city', sa.String(length=100), nullable=False),
    sa.Column('geolocation_state', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geolocation_geolocation_zip_code_prefix'), 'geolocation', ['geolocation_zip_code_prefix'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=True),
    sa.Column('snapshot_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notification_severity_enum', create_constraint=True), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('responsible_agent', sa.String(length=50), nullable=True),
    sa.Column('target_role', sa.Enum('SUPER_ADMIN', 'INVENTORY_ADMIN', 'ORDERS_ADMIN', 'CUSTOMER_SUPPORT_ADMIN', 'PRICING_ADMIN', 'MARKETING_ADMIN', 'LOGISTICS_ADMIN', name='notification_target_role_enum', create_constraint=True), nullable=True),
    sa.Column('target_user_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ACKNOWLEDGED', 'RESOLVED', name='notification_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_agent_status', 'notifications', ['responsible_agent', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_execution_id'), 'notifications', ['execution_id'], unique=False)
    op.create_index(op.f('ix_notifications_fingerprint'), 'notifications', ['fingerprint'], unique=False)
    op.create_index('ix_notifications_fingerprint_status', 'notifications', ['fingerprint', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_responsible_agent'), 'notifications', ['responsible_agent'], unique=False)
    op.create_index(op.f('ix_notifications_snapshot_id'), 'notifications', ['snapshot_id'], unique=False)
    op.create_index('ix_notifications_status_role', 'notifications', ['status', 'target_role'], unique=False)
    op.create_index(op.f('ix_notifications_target_role'), 'notifications', ['target_role'], unique=False)
    op.create_index(op.f('ix_notifications_target_user_id'), 'notifications', ['target_user_id'], unique=False)
    op.create_table('orchestration_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=60), nullable=False),
    sa.Column('overall_health', sa.String(length=24), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('systemic_findings', sa.JSON(), nullable=True),
    sa.Column('conflicts', sa.JSON(), nullable=True),
    sa.Column('priority_actions', sa.JSON(), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('llm_backed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestration_decisions_created_at'), 'orchestration_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_orchestration_decisions_execution_id'), 'orchestration_decisions', ['execution_id'], unique=False)
    op.create_table('product_category_name_translation',
    sa.Column('product_category_name', sa.String(length=100), nullable=False),
    sa.Column('product_category_name_english', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('product_category_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('product_category_name', sa.String(length=100), nullable=True),
    sa.Column('product_name_lenght', sa.Integer(), nullable=True),
    sa.Column('product_description_lenght', sa.Integer(), nullable=True),
    sa.Column('product_photos_qty', sa.Integer(), nullable=True),
    sa.Column('product_weight_g', sa.Float(), nullable=True),
    sa.Column('product_length_cm', sa.Float(), nullable=True),
    sa.Column('product_height_cm', sa.Float(), nullable=True),
    sa.Column('product_width_cm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_category_name'), 'products', ['product_category_name'], unique=False)
    op.create_table('sellers',
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('seller_zip_code_prefix', sa.Integer(), nullable=False),
    sa.Column('seller_city', sa.String(length=100), nullable=False),
    sa.Column('seller_state', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_index(op.f('ix_sellers_seller_zip_code_prefix'), 'sellers', ['seller_zip_code_prefix'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_ts'), 'stock_movements', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'INVENTORY_ADMIN', 'ORDERS_ADMIN', 'CUSTOMER_SUPPORT_ADMIN', 'PRICING_ADMIN', 'MARKETING_ADMIN', 'LOGISTICS_ADMIN', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('what_happened', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data_status', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_findings_agent'), 'agent_findings', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_findings_run_id'), 'agent_findings', ['run_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('llm_backed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_table('dataco_order_items',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_card_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('department_name', sa.String(length=100), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('order_item_quantity', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('order_item_discount', sa.Float(), nullable=False),
    sa.Column('order_item_discount_rate', sa.Float(), nullable=False),
    sa.Column('order_item_total', sa.Float(), nullable=False),
    sa.Column('order_item_profit_ratio', sa.Float(), nullable=False),
    sa.Column('order_profit_per_order', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['dataco_orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_dataco_order_items_category_id'), 'dataco_order_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_dataco_order_items_order_id'), 'dataco_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_dataco_order_items_product_card_id'), 'dataco_order_items', ['product_card_id'], unique=False)
    op.create_table('inventory',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('data_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('order_purchase_timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_approved_at', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_carrier_date', sa.DateTime(), nullable=True),
    sa.Column('order_delivered_customer_date', sa.DateTime(), nullable=True),
    sa.Column('order_estimated_delivery_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_purchase_timestamp'), 'orders', ['order_purchase_timestamp'], unique=False)
    op.create_index(op.f('ix_orders_order_status'), 'orders', ['order_status'], unique=False)
    op.create_table('automation_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['orchestration_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['agent_findings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_actions_action_type'), 'automation_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_automation_actions_agent'), 'automation_actions', ['agent'], unique=False)
    op.create_index(op.f('ix_automation_actions_created_at'), 'automation_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_actions_status'), 'automation_actions', ['status'], unique=False)
    op.create_index('ix_automation_status_created', 'automation_actions', ['status', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.String(length=32), nullable=False),
    sa.Column('shipping_limit_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('freight_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'order_item_id')
    )
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_items_seller_id'), 'order_items', ['seller_id'], unique=False)
    op.create_table('order_payments',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('payment_sequential', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_installments', sa.Integer(), nullable=False),
    sa.Column('payment_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'payment_sequential')
    )
    op.create_table('order_reviews',
    sa.Column('review_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=False),
    sa.Column('review_comment_title', sa.Text(), nullable=True),
    sa.Column('review_comment_message', sa.Text(), nullable=True),
    sa.Column('review_creation_date', sa.DateTime(), nullable=False),
    sa.Column('review_answer_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('review_id', 'order_id')
    )
    op.create_index(op.f('ix_order_reviews_review_creation_date'), 'order_reviews', ['review_creation_date'], unique=False)
    op.create_index(op.f('ix_order_reviews_review_score'), 'order_reviews', ['review_score'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('required_role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['automation_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_index(op.f('ix_approvals_required_role'), 'approvals', ['required_role'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_required_role'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_order_reviews_review_score'), table_name='order_reviews')
    op.drop_index(op.f('ix_order_reviews_review_creation_date'), table_name='order_reviews')
    op.drop_table('order_reviews')
    op.drop_table('order_payments')
    op.drop_index(op.f('ix_order_items_seller_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_automation_status_created', table_name='automation_actions')
    op.drop_index(op.f('ix_automation_actions_status'), table_name='automation_actions')
    op.drop_index(op.f('ix_automation_actions_created_at'), table_name='automation_actions')
    op.drop_index(op.f('ix_automation_actions_agent'), table_name='automation_actions')
    op.drop_index(op.f('ix_automation_actions_action_type'), table_name='automation_actions')
    op.drop_table('automation_actions')
    op.drop_index(op.f('ix_orders_order_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_purchase_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_dataco_order_items_product_card_id'), table_name='dataco_order_items')
    op.drop_index(op.f('ix_dataco_order_items_order_id'), table_name='dataco_order_items')
    op.drop_index(op.f('ix_dataco_order_items_category_id'), table_name='dataco_order_items')
    op.drop_table('dataco_order_items')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_agent_findings_run_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_agent'), table_name='agent_findings')
    op.drop_table('agent_findings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_movements_ts'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_sellers_seller_zip_code_prefix'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_products_product_category_name'), table_name='products')
    op.drop_table('products')
    op.drop_table('product_category_name_translation')
    op.drop_index(op.f('ix_orchestration_decisions_execution_id'), table_name='orchestration_decisions')
    op.drop_index(op.f('ix_orchestration_decisions_created_at'), table_name='orchestration_decisions')
    op.drop_table('orchestration_decisions')
    op.drop_index(op.f('ix_notifications_target_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_role'), table_name='notifications')
    op.drop_index('ix_notifications_status_role', table_name='notifications')
    op.drop_index(op.f('ix_notifications_snapshot_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_responsible_agent'), table_name='notifications')
    op.drop_index('ix_notifications_fingerprint_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_fingerprint'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_execution_id'), table_name='notifications')
    op.drop_index('ix_notifications_agent_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_geolocation_geolocation_zip_code_prefix'), table_name='geolocation')
    op.drop_table('geolocation')
    op.drop_index(op.f('ix_dataco_orders_source'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_shipping_mode'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_order_status'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_order_region'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_order_date'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_market'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_late_delivery_risk'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_customer_id'), table_name='dataco_orders')
    op.drop_table('dataco_orders')
    op.drop_index(op.f('ix_customers_customer_zip_code_prefix'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_unique_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('customer_memory')
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_ref'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_started_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_execution_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_agent_started', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_predictions_snapshot_id'), table_name='agent_predictions')
    op.drop_index(op.f('ix_agent_predictions_execution_id'), table_name='agent_predictions')
    op.drop_index('ix_agent_predictions_exec_agent', table_name='agent_predictions')
    op.drop_index(op.f('ix_agent_predictions_agent_id'), table_name='agent_predictions')
    op.drop_table('agent_predictions')
    # ### end Alembic commands ###
